### ISSUE TITLE
Only support mono soundtrack?

### ISSUE THREAD

**Issue by NyaMisty** [leo-so/VocalMelodyExtPatchCNN#1]
It seems that the STFT in your script will fail if there is two soundtrack in the file.

**Comment by leo-so** [comment]
> It seems that the STFT in your script will fail if there is two soundtrack in the file.

Currently the script allows mono-channel input signals only (and the algorithm is also designed for mono-channel signals). If you are using multi-channel signals, just convert it into a mono-channel one.

**Comment by NyaMisty** [comment]
OK, I got it~ Thanks~~
